### PR TITLE
Bugfix for const expressions

### PR DESCRIPTION
**Pull request by wedesoft**
* added test for retrieving constant
* removed call to ".address" from const function

### CODE REVIEW

**Review by IGJoshua — APPROVED** [review]
This looks great to me, feel kinda silly I missed it, but that's what I get for not having enough tests, gonna merge this soon.

**Comment by wedesoft** [comment]
Ok, no problem. Great library btw :)

**Comment by IGJoshua** [comment]
This is merged in 26fbed6927ca588fb5c667420333de73ef7f95eb, although unfortunately because of how github works the fact that I did a rebase to apply this to develop instead of master this counts as "closed" instead of merged.

I really don't like that github does it this way.

**Comment by wedesoft** [comment]
Ok, that's strange. Thanks for letting me know.

**Pull request closed without merging**
